services:
  memcached:
    image: memcached:1.6-alpine
    container_name: blog-memcached
    restart: unless-stopped
    ports:
      - "11330:11211"
    command:
      - memcached
      - -m
      - "256"
      - -c
      - "1024"
      - -v

  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habersitesi-backend
    restart: unless-stopped
    ports:
      - "5190:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Memcached__Host=blog-memcached
      - Memcached__Port=11211
      - SiteBlogLink=http://localhost:5190/blog
      - JWT__ValidAudience=http://localhost:3000
      - JWT__ValidIssuer=http://localhost:5190
      - Cors__AllowedOrigins=http://localhost:3000
    depends_on:
      - memcached

